steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true

- script: yarn
  displayName: Yarn Install Dependencies

- script: yarn test
  timeoutInMinutes: 5
  displayName: Run Tests

- script: yarn build
  timeoutInMinutes: 5
  displayName: Build

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: build\
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: Copy Files

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact