steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
  inputs:
    versionSpec: 1.16.x
    checkLatest: true


- powershell: |
    yarn
  displayName: Yarn Install Dependencies